import pytest
from fastapi.testclient import TestClient
from backend.models import SystemIncident, HealthThresholdConfiguration, SystemHealthSnapshot
from datetime import datetime, UTC

def test_liveness_check(client):
    r = client.get("/health/live")
    assert r.status_code == 200
    data = r.json()
    assert data["status"] == "healthy"
    assert "uptime_seconds" in data
    assert "timestamp" in data


def test_readiness_check(client):
    r = client.get("/health/ready")
    assert r.status_code == 200
    data = r.json()
    assert data["status"] == "healthy"
    assert data["database"] == "ready"


def test_health_db_check(client):
    r = client.get("/health/db")
    assert r.status_code == 200
    data = r.json()
    assert data["status"] == "ok"
    assert data["component"] == "PostgreSQL Database"
    assert "migration_state" in data
    assert "current_revision" in data


def test_request_correlation_id_middleware(client):
    # 1. Autogenerated ID
    r = client.get("/health/live")
    assert r.status_code == 200
    assert "X-Request-ID" in r.headers
    req_id = r.headers["X-Request-ID"]
    assert len(req_id) > 10

    # 2. Reflected client-passed ID
    custom_id = "test-correlation-uuid-12345"
    r2 = client.get("/health/live", headers={"X-Request-ID": custom_id})
    assert r2.status_code == 200
    assert r2.headers["X-Request-ID"] == custom_id


def test_system_health_telemetry_auth(client):
    # 1. Unauthenticated gets 401
    r = client.get("/api/system/health")
    assert r.status_code == 401


def test_system_health_telemetry_success(client, db, admin_token):
    # Seed a threshold config to make sure the API can load it
    db.query(HealthThresholdConfiguration).delete()
    db.add(HealthThresholdConfiguration(key="database_latency_warning_ms", value=100.0, description="DB Latency Warn"))
    db.commit()

    headers = {"Authorization": f"Bearer {admin_token}"}
    r = client.get("/api/system/health", headers=headers)
    assert r.status_code == 200
    data = r.json()
    
    assert "overall_status" in data
    assert "database" in data
    assert "redis" in data
    assert "rabbitmq" in data
    assert "celery" in data
    assert "email" in data
    assert "backup" in data
    assert "sentry" in data
    assert "gemini" in data
    assert "cloudflare" in data
    assert "simulation" in data
    assert "application" in data


def test_thresholds_management_rbac(client, db, admin_token, manager_token):
    # Clear and seed default thresholds
    db.query(HealthThresholdConfiguration).delete()
    db.add(HealthThresholdConfiguration(key="api_latency_warning_ms", value=300.0, description="Warn"))
    db.commit()

    headers_admin = {"Authorization": f"Bearer {admin_token}"}
    
    # 1. Get thresholds
    r_get = client.get("/api/system/thresholds", headers=headers_admin)
    assert r_get.status_code == 200
    assert len(r_get.json()) > 0

    # 2. Form validation: negative number rejected
    r_put_neg = client.put(
        "/api/system/thresholds",
        json={"api_latency_warning_ms": -50.0},
        headers=headers_admin
    )
    assert r_put_neg.status_code == 400
    assert "positive non-zero numbers" in r_put_neg.json()["message"]

    # 3. Successful update by admin
    r_put = client.put(
        "/api/system/thresholds",
        json={"api_latency_warning_ms": 400.0},
        headers=headers_admin
    )
    assert r_put.status_code == 200
    
    # Verify value changed in DB
    db.expire_all()
    config = db.query(HealthThresholdConfiguration).filter(HealthThresholdConfiguration.key == "api_latency_warning_ms").first()
    assert config.value == 400.0


def test_incidents_management_workflow(client, db, admin_token, manager_token):
    # Seed an open incident
    db.query(SystemIncident).delete()
    inc = SystemIncident(
        category="DATABASE",
        severity="CRITICAL",
        title="Postgres Connection Fail",
        description="Database disconnected during test",
        source="test",
        status="OPEN",
        fingerprint="TEST_DB_OFFLINE",
        started_at=datetime.now(UTC).replace(tzinfo=None)
    )
    db.add(inc)
    db.commit()
    db.refresh(inc)

    headers_manager = {"Authorization": f"Bearer {manager_token}"}

    # 1. Get incidents
    r_list = client.get("/api/system/incidents", headers=headers_manager)
    assert r_list.status_code == 200
    assert len(r_list.json()) > 0
    assert r_list.json()[0]["fingerprint"] == "TEST_DB_OFFLINE"

    # 2. Acknowledge incident
    r_ack = client.post(f"/api/system/incidents/{inc.id}/acknowledge", headers=headers_manager)
    assert r_ack.status_code == 200
    
    # Verify status in DB
    db.expire_all()
    inc_db = db.query(SystemIncident).filter(SystemIncident.id == inc.id).first()
    assert inc_db.status == "ACKNOWLEDGED"

    # 3. Resolve incident
    r_res = client.post(f"/api/system/incidents/{inc.id}/resolve", headers=headers_manager)
    assert r_res.status_code == 200
    
    # Verify resolved status and resolved_at
    db.expire_all()
    inc_db = db.query(SystemIncident).filter(SystemIncident.id == inc.id).first()
    assert inc_db.status == "RESOLVED"
    assert inc_db.resolved_at is not None
