"""add_incoming_shipments_table

Revision ID: 0785d92af078
Revises: c6a0f47c242e
Create Date: 2026-08-21 12:14:25.886750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0785d92af078'
down_revision: Union[str, Sequence[str], None] = 'c6a0f47c242e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_shipments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('qc_result', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('qc_at', sa.DateTime(), nullable=True),
    sa.Column('putaway_at', sa.DateTime(), nullable=True),
    sa.Column('responsible_user', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_shipments_item_id'), 'incoming_shipments', ['item_id'], unique=False)
    op.create_index(op.f('ix_incoming_shipments_status'), 'incoming_shipments', ['status'], unique=False)
    op.create_index(op.f('ix_incoming_shipments_warehouse_id'), 'incoming_shipments', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_shipments_warehouse_id'), table_name='incoming_shipments')
    op.drop_index(op.f('ix_incoming_shipments_status'), table_name='incoming_shipments')
    op.drop_index(op.f('ix_incoming_shipments_item_id'), table_name='incoming_shipments')
    op.drop_table('incoming_shipments')
    # ### end Alembic commands ###
