"""phase10_notifications

Revision ID: 3bbcc0985a4e
Revises: d9e8f7a6b5c4
Create Date: 2026-08-19 09:53:29.484141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bbcc0985a4e'
down_revision: Union[str, Sequence[str], None] = 'd9e8f7a6b5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_user_category_preference')
    )
    op.create_index(op.f('ix_notification_preferences_category'), 'notification_preferences', ['category'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=True),
    sa.Column('source_entity_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_warehouse_id'), 'notifications', ['warehouse_id'], unique=False)
    op.create_table('user_warehouse_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'warehouse_id', name='uq_user_warehouse')
    )
    op.create_index(op.f('ix_user_warehouse_access_user_id'), 'user_warehouse_access', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_warehouse_access_warehouse_id'), 'user_warehouse_access', ['warehouse_id'], unique=False)
    op.alter_column('ai_recommendations', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'confidence_or_reliability',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'supporting_metrics',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_air_created_at'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_air_rec_type'), table_name='ai_recommendations')
    op.create_index(op.f('ix_ai_recommendations_created_at'), 'ai_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_recommendation_type'), 'ai_recommendations', ['recommendation_type'], unique=False)
    op.alter_column('digital_twin_simulations', 'simulation_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'simulation_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'speed_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'seed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'scenario_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'tick_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'created_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_dts_created_at'), table_name='digital_twin_simulations')
    op.drop_index(op.f('ix_dts_status'), table_name='digital_twin_simulations')
    op.drop_index(op.f('ix_dts_warehouse_id'), table_name='digital_twin_simulations')
    op.create_index(op.f('ix_digital_twin_simulations_created_at'), 'digital_twin_simulations', ['created_at'], unique=False)
    op.create_index(op.f('ix_digital_twin_simulations_simulation_status'), 'digital_twin_simulations', ['simulation_status'], unique=False)
    op.create_index(op.f('ix_digital_twin_simulations_warehouse_id'), 'digital_twin_simulations', ['warehouse_id'], unique=False)
    op.alter_column('otp_records', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('otp_records', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('otp_records', 'context_data',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_otp_expires_at'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_user_purpose'), table_name='otp_records')
    op.create_index(op.f('ix_otp_records_expires_at'), 'otp_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_records_user_id'), 'otp_records', ['user_id'], unique=False)
    op.create_unique_constraint('uq_otp_user_purpose', 'otp_records', ['user_id', 'purpose'])
    op.drop_column('otp_records', 'metadata')
    op.alter_column('simulation_events', 'severity',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_events', 'sim_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_events', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_se_event_type'), table_name='simulation_events')
    op.drop_index(op.f('ix_se_real_timestamp'), table_name='simulation_events')
    op.drop_index(op.f('ix_se_robot_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_se_simulation_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_se_task_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_se_warehouse_id'), table_name='simulation_events')
    op.create_index(op.f('ix_simulation_events_event_type'), 'simulation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_simulation_events_real_timestamp'), 'simulation_events', ['real_timestamp'], unique=False)
    op.create_index(op.f('ix_simulation_events_robot_id'), 'simulation_events', ['robot_id'], unique=False)
    op.create_index(op.f('ix_simulation_events_simulation_id'), 'simulation_events', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulation_events_task_id'), 'simulation_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_simulation_events_warehouse_id'), 'simulation_events', ['warehouse_id'], unique=False)
    op.alter_column('simulation_snapshots', 'snapshot_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'sim_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'robot_states',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'task_states',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'obstacle_states',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'sim_inventory_delta',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_ss_simulation_id'), table_name='simulation_snapshots')
    op.drop_index(op.f('ix_ss_warehouse_id'), table_name='simulation_snapshots')
    op.create_index(op.f('ix_simulation_snapshots_simulation_id'), 'simulation_snapshots', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_simulation_snapshots_warehouse_id'), 'simulation_snapshots', ['warehouse_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'failed_login_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'failed_login_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_simulation_snapshots_warehouse_id'), table_name='simulation_snapshots')
    op.drop_index(op.f('ix_simulation_snapshots_simulation_id'), table_name='simulation_snapshots')
    op.create_index(op.f('ix_ss_warehouse_id'), 'simulation_snapshots', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_ss_simulation_id'), 'simulation_snapshots', ['simulation_id'], unique=False)
    op.alter_column('simulation_snapshots', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'sim_inventory_delta',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'obstacle_states',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'::text"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'task_states',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'::text"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'robot_states',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'::text"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'sim_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('simulation_snapshots', 'snapshot_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_simulation_events_warehouse_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_task_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_simulation_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_robot_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_real_timestamp'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_event_type'), table_name='simulation_events')
    op.create_index(op.f('ix_se_warehouse_id'), 'simulation_events', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_se_task_id'), 'simulation_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_se_simulation_id'), 'simulation_events', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_se_robot_id'), 'simulation_events', ['robot_id'], unique=False)
    op.create_index(op.f('ix_se_real_timestamp'), 'simulation_events', ['real_timestamp'], unique=False)
    op.create_index(op.f('ix_se_event_type'), 'simulation_events', ['event_type'], unique=False)
    op.alter_column('simulation_events', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('simulation_events', 'sim_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('simulation_events', 'severity',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.add_column('otp_records', sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True))
    op.drop_constraint('uq_otp_user_purpose', 'otp_records', type_='unique')
    op.drop_index(op.f('ix_otp_records_user_id'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_expires_at'), table_name='otp_records')
    op.create_index(op.f('ix_otp_user_purpose'), 'otp_records', ['user_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_otp_expires_at'), 'otp_records', ['expires_at'], unique=False)
    op.alter_column('otp_records', 'context_data',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=True)
    op.alter_column('otp_records', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('otp_records', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_digital_twin_simulations_warehouse_id'), table_name='digital_twin_simulations')
    op.drop_index(op.f('ix_digital_twin_simulations_simulation_status'), table_name='digital_twin_simulations')
    op.drop_index(op.f('ix_digital_twin_simulations_created_at'), table_name='digital_twin_simulations')
    op.create_index(op.f('ix_dts_warehouse_id'), 'digital_twin_simulations', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_dts_status'), 'digital_twin_simulations', ['simulation_status'], unique=False)
    op.create_index(op.f('ix_dts_created_at'), 'digital_twin_simulations', ['created_at'], unique=False)
    op.alter_column('digital_twin_simulations', 'created_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'system'::character varying"),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'tick_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'scenario_type',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'NORMAL_OPERATIONS'::character varying"),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'OBSERVATION'::character varying"),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'seed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('42'),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'speed_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'simulation_time_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('digital_twin_simulations', 'simulation_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'IDLE'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_recommendations_recommendation_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_created_at'), table_name='ai_recommendations')
    op.create_index(op.f('ix_air_rec_type'), 'ai_recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_air_created_at'), 'ai_recommendations', ['created_at'], unique=False)
    op.alter_column('ai_recommendations', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('ai_recommendations', 'supporting_metrics',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'confidence_or_reliability',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'HIGH'::character varying"),
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('ai_recommendations', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'MEDIUM'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_warehouse_access_warehouse_id'), table_name='user_warehouse_access')
    op.drop_index(op.f('ix_user_warehouse_access_user_id'), table_name='user_warehouse_access')
    op.drop_table('user_warehouse_access')
    op.drop_index(op.f('ix_notifications_warehouse_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_category'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
