"""add_warehouse_id_to_financial_transaction

Revision ID: 4252c662336c
Revises: e38bbe1ee205
Create Date: 2026-08-21 15:51:27.307372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4252c662336c'
down_revision: Union[str, Sequence[str], None] = 'e38bbe1ee205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_transactions', sa.Column('warehouse_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_financial_transactions_warehouse_id'), 'financial_transactions', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'financial_transactions', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_financial_transactions_warehouse_id'), table_name='financial_transactions')
    op.drop_column('financial_transactions', 'warehouse_id')
    # ### end Alembic commands ###
