"""add_simulation_tables

Revision ID: 6d003dd2cc3e
Revises: f1a2b3c4d5e6
Create Date: 2026-08-21 23:15:51.243632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d003dd2cc3e'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('simulation_duration', sa.Float(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_warehouse_id'), 'simulation_runs', ['warehouse_id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_simulation_run_id'), 'simulation_results', ['simulation_run_id'], unique=False)
    op.alter_column('abc_classifications', 'total_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('abc_classifications', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('abc_classifications', 'pct_contribution',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('abc_classifications', 'cumulative_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('abc_classifications', 'threshold_a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('abc_classifications', 'threshold_b',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anomaly_results', 'is_anomaly',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anomaly_results', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anomaly_results', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_forecast_results_entity_date'), table_name='forecast_results')
    op.create_index(op.f('ix_forecast_results_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.alter_column('forecast_runs', 'horizon_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('replenishment_recommendations', 'urgency',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('replenishment_recommendations', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('replenishment_recommendations', 'data_quality',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_replenishment_created_at'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_item_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_urgency'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_warehouse_id'), table_name='replenishment_recommendations')
    op.create_index(op.f('ix_replenishment_recommendations_created_at'), 'replenishment_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_item_id'), 'replenishment_recommendations', ['item_id'], unique=False)
    op.create_index(op.f('ix_replenishment_recommendations_warehouse_id'), 'replenishment_recommendations', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replenishment_recommendations_warehouse_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_item_id'), table_name='replenishment_recommendations')
    op.drop_index(op.f('ix_replenishment_recommendations_created_at'), table_name='replenishment_recommendations')
    op.create_index(op.f('ix_replenishment_warehouse_id'), 'replenishment_recommendations', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_replenishment_urgency'), 'replenishment_recommendations', ['urgency'], unique=False)
    op.create_index(op.f('ix_replenishment_item_id'), 'replenishment_recommendations', ['item_id'], unique=False)
    op.create_index(op.f('ix_replenishment_created_at'), 'replenishment_recommendations', ['created_at'], unique=False)
    op.alter_column('replenishment_recommendations', 'data_quality',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'COMPLETE'::character varying"),
               existing_nullable=False)
    op.alter_column('replenishment_recommendations', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'NO_ACTION'::character varying"),
               existing_nullable=False)
    op.alter_column('replenishment_recommendations', 'urgency',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'NO_ACTION'::character varying"),
               existing_nullable=False)
    op.alter_column('forecast_runs', 'horizon_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('28'),
               existing_nullable=False)
    op.drop_index(op.f('ix_forecast_results_forecast_date'), table_name='forecast_results')
    op.create_index(op.f('ix_forecast_results_entity_date'), 'forecast_results', ['entity', 'forecast_date'], unique=False)
    op.alter_column('anomaly_results', 'model_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0'::character varying"),
               existing_nullable=False)
    op.alter_column('anomaly_results', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'IsolationForest'::character varying"),
               existing_nullable=False)
    op.alter_column('anomaly_results', 'is_anomaly',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'threshold_b',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'95'::double precision"),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'threshold_a',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'80'::double precision"),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'cumulative_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'pct_contribution',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('abc_classifications', 'total_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.drop_index(op.f('ix_simulation_results_simulation_run_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_simulation_runs_warehouse_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
