"""add_wms_core_tables

Revision ID: ba82c39c98ef
Revises: 5724cd882171
Create Date: 2026-08-17 23:45:47.282521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba82c39c98ef'
down_revision: Union[str, Sequence[str], None] = '5724cd882171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    op.create_table('warehouse_locations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('aisle', sa.String(length=20), nullable=False),
    sa.Column('rack', sa.String(length=20), nullable=False),
    sa.Column('shelf', sa.String(length=20), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_utilization', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_locations_warehouse_id'), 'warehouse_locations', ['warehouse_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('damaged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'item_id', 'location_id', name='uq_warehouse_item_location')
    )
    op.create_index(op.f('ix_inventory_item_id'), 'inventory', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_location_id'), 'inventory', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('released_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_created_at'), 'inventory_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_item_id'), 'inventory_reservations', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_location_id'), 'inventory_reservations', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'inventory_reservations', ['order_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_events_timestamp'), 'order_events', ['timestamp'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('requested_qty', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('picked_qty', sa.Integer(), nullable=False),
    sa.Column('packed_qty', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('packing_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_records_order_id'), 'packing_records', ['order_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_reference', sa.String(length=100), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_table('picking_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('picked_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_tasks_item_id'), 'picking_tasks', ['item_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_location_id'), 'picking_tasks', ['location_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_order_id'), 'picking_tasks', ['order_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_order_item_id'), 'picking_tasks', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_status'), 'picking_tasks', ['status'], unique=False)
    op.add_column('items', sa.Column('sku', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('items', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('dimensions', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('barcode', sa.String(length=64), nullable=True))
    op.add_column('items', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('reorder_threshold', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('preferred_storage_type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_column('items', 'preferred_storage_type')
    op.drop_column('items', 'reorder_threshold')
    op.drop_column('items', 'is_active')
    op.drop_column('items', 'barcode')
    op.drop_column('items', 'dimensions')
    op.drop_column('items', 'weight_kg')
    op.drop_column('items', 'unit')
    op.drop_column('items', 'description')
    op.drop_column('items', 'sku')
    op.drop_index(op.f('ix_picking_tasks_status'), table_name='picking_tasks')
    op.drop_index(op.f('ix_picking_tasks_order_item_id'), table_name='picking_tasks')
    op.drop_index(op.f('ix_picking_tasks_order_id'), table_name='picking_tasks')
    op.drop_index(op.f('ix_picking_tasks_location_id'), table_name='picking_tasks')
    op.drop_index(op.f('ix_picking_tasks_item_id'), table_name='picking_tasks')
    op.drop_table('picking_tasks')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_packing_records_order_id'), table_name='packing_records')
    op.drop_table('packing_records')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_events_timestamp'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_location_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_item_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_created_at'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_location_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_item_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_warehouse_locations_warehouse_id'), table_name='warehouse_locations')
    op.drop_table('warehouse_locations')
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
