"""add_system_health_and_incident_models

Revision ID: c6a0f47c242e
Revises: db951531d664
Create Date: 2026-08-19 19:06:57.633101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a0f47c242e'
down_revision: Union[str, Sequence[str], None] = 'db951531d664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_thresholds_key'), 'health_thresholds', ['key'], unique=True)
    op.create_table('system_health_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_snapshots_service'), 'system_health_snapshots', ['service'], unique=False)
    op.create_index(op.f('ix_system_health_snapshots_timestamp'), 'system_health_snapshots', ['timestamp'], unique=False)
    op.create_table('system_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_incidents_category'), 'system_incidents', ['category'], unique=False)
    op.create_index(op.f('ix_system_incidents_fingerprint'), 'system_incidents', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_incidents_fingerprint'), table_name='system_incidents')
    op.drop_index(op.f('ix_system_incidents_category'), table_name='system_incidents')
    op.drop_table('system_incidents')
    op.drop_index(op.f('ix_system_health_snapshots_timestamp'), table_name='system_health_snapshots')
    op.drop_index(op.f('ix_system_health_snapshots_service'), table_name='system_health_snapshots')
    op.drop_table('system_health_snapshots')
    op.drop_index(op.f('ix_health_thresholds_key'), table_name='health_thresholds')
    op.drop_table('health_thresholds')
    # ### end Alembic commands ###
