"""add_robot_fleet_tables

Revision ID: dbf8748ff321
Revises: 451740f1aa10
Create Date: 2026-08-18 19:52:14.360768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf8748ff321'
down_revision: Union[str, Sequence[str], None] = '451740f1aa10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.Column('current_location_id', sa.String(length=50), nullable=True),
    sa.Column('current_x', sa.Float(), nullable=False),
    sa.Column('current_y', sa.Float(), nullable=False),
    sa.Column('target_location_id', sa.String(length=50), nullable=True),
    sa.Column('target_x', sa.Float(), nullable=False),
    sa.Column('target_y', sa.Float(), nullable=False),
    sa.Column('assigned_task_id', sa.Integer(), nullable=True),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('total_operating_time', sa.Float(), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('robot_type', sa.String(length=30), nullable=False),
    sa.Column('max_payload', sa.Float(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_assigned_task_id'), 'robots', ['assigned_task_id'], unique=False)
    op.create_index(op.f('ix_robots_current_location_id'), 'robots', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_robots_robot_code'), 'robots', ['robot_code'], unique=True)
    op.create_index(op.f('ix_robots_status'), 'robots', ['status'], unique=False)
    op.create_index(op.f('ix_robots_target_location_id'), 'robots', ['target_location_id'], unique=False)
    op.create_index(op.f('ix_robots_warehouse_id'), 'robots', ['warehouse_id'], unique=False)
    op.create_table('robot_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_telemetry_robot_id'), 'robot_telemetry', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_telemetry_timestamp'), 'robot_telemetry', ['timestamp'], unique=False)
    op.alter_column('task_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('task_events', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'priority_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('tasks', 'order_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tasks', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_picking_tasks_item_id'), table_name='tasks')
    op.drop_index(op.f('ix_picking_tasks_location_id'), table_name='tasks')
    op.drop_index(op.f('ix_picking_tasks_order_id'), table_name='tasks')
    op.drop_index(op.f('ix_picking_tasks_order_item_id'), table_name='tasks')
    op.drop_index(op.f('ix_picking_tasks_status'), table_name='tasks')
    op.drop_constraint(op.f('uq_tasks_task_number'), 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_destination_location_id'), 'tasks', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_tasks_order_item_id'), 'tasks', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_tasks_source_location_id'), 'tasks', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_number'), 'tasks', ['task_number'], unique=True)
    op.drop_column('tasks', 'operator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('operator', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_task_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_location_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_order_item_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_destination_location_id'), table_name='tasks')
    op.create_unique_constraint(op.f('uq_tasks_task_number'), 'tasks', ['task_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_picking_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_picking_tasks_order_item_id'), 'tasks', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_order_id'), 'tasks', ['order_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_location_id'), 'tasks', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_picking_tasks_item_id'), 'tasks', ['product_id'], unique=False)
    op.alter_column('tasks', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tasks', 'order_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'order_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('tasks', 'priority_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'MEDIUM'::character varying"),
               existing_nullable=False)
    op.alter_column('task_events', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'::text"),
               existing_nullable=False)
    op.alter_column('task_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_robot_telemetry_timestamp'), table_name='robot_telemetry')
    op.drop_index(op.f('ix_robot_telemetry_robot_id'), table_name='robot_telemetry')
    op.drop_table('robot_telemetry')
    op.drop_index(op.f('ix_robots_warehouse_id'), table_name='robots')
    op.drop_index(op.f('ix_robots_target_location_id'), table_name='robots')
    op.drop_index(op.f('ix_robots_status'), table_name='robots')
    op.drop_index(op.f('ix_robots_robot_code'), table_name='robots')
    op.drop_index(op.f('ix_robots_current_location_id'), table_name='robots')
    op.drop_index(op.f('ix_robots_assigned_task_id'), table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
