"""modify_robot_id_type

Revision ID: e38bbe1ee205
Revises: c065d057ff54
Create Date: 2026-08-21 14:51:03.376372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38bbe1ee205'
down_revision: Union[str, Sequence[str], None] = 'c065d057ff54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_movements_robot_id_fkey'), 'inventory_movements', type_='foreignkey')
    op.alter_column('inventory_movements', 'robot_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_foreign_key(None, 'inventory_movements', 'robots', ['robot_id'], ['robot_code'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_movements_robot_id_fkey'), 'inventory_movements', 'robots', ['robot_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_movements', 'robot_id',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
