"""add_warehouse_id_to_intelligence_tables

Revision ID: e47dfd77a741
Revises: e90bcac0ce85
Create Date: 2026-08-22 23:40:11.546651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47dfd77a741'
down_revision: Union[str, Sequence[str], None] = 'e90bcac0ce85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abc_classifications', sa.Column('warehouse_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_abc_classifications_warehouse_id'), 'abc_classifications', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'abc_classifications', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('anomaly_results', sa.Column('warehouse_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_anomaly_results_warehouse_id'), 'anomaly_results', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'anomaly_results', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.add_column('forecast_runs', sa.Column('warehouse_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_forecast_runs_warehouse_id'), 'forecast_runs', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'forecast_runs', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forecast_runs', type_='foreignkey')
    op.drop_index(op.f('ix_forecast_runs_warehouse_id'), table_name='forecast_runs')
    op.drop_column('forecast_runs', 'warehouse_id')
    op.drop_constraint(None, 'anomaly_results', type_='foreignkey')
    op.drop_index(op.f('ix_anomaly_results_warehouse_id'), table_name='anomaly_results')
    op.drop_column('anomaly_results', 'warehouse_id')
    op.drop_constraint(None, 'abc_classifications', type_='foreignkey')
    op.drop_index(op.f('ix_abc_classifications_warehouse_id'), table_name='abc_classifications')
    op.drop_column('abc_classifications', 'warehouse_id')
    # ### end Alembic commands ###
