"""add_operational_wms_tables

Revision ID: e90bcac0ce85
Revises: d7a56c15d0ad
Create Date: 2026-08-22 23:07:26.966937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90bcac0ce85'
down_revision: Union[str, Sequence[str], None] = 'd7a56c15d0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_requests',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('source_warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('destination_warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requester', sa.String(length=64), nullable=False),
    sa.Column('approver', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_requests_destination_warehouse_id'), 'transfer_requests', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_source_warehouse_id'), 'transfer_requests', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_status'), 'transfer_requests', ['status'], unique=False)
    op.create_table('damage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_records_item_id'), 'damage_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_damage_records_location_id'), 'damage_records', ['location_id'], unique=False)
    op.create_index(op.f('ix_damage_records_timestamp'), 'damage_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_damage_records_warehouse_id'), 'damage_records', ['warehouse_id'], unique=False)
    op.create_table('quality_control_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('quantity_passed', sa.Integer(), nullable=False),
    sa.Column('quantity_failed', sa.Integer(), nullable=False),
    sa.Column('inspector', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['incoming_shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_control_records_item_id'), 'quality_control_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_quality_control_records_shipment_id'), 'quality_control_records', ['shipment_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_requests_status'), 'return_requests', ['status'], unique=False)
    op.create_index(op.f('ix_return_requests_warehouse_id'), 'return_requests', ['warehouse_id'], unique=False)
    op.create_table('transfer_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.String(length=50), nullable=True),
    sa.Column('destination_location_id', sa.String(length=50), nullable=True),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_items_item_id'), 'transfer_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_transfer_items_transfer_id'), 'transfer_items', ['transfer_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['return_id'], ['return_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_item_id'), 'return_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_item_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_transfer_items_transfer_id'), table_name='transfer_items')
    op.drop_index(op.f('ix_transfer_items_item_id'), table_name='transfer_items')
    op.drop_table('transfer_items')
    op.drop_index(op.f('ix_return_requests_warehouse_id'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_status'), table_name='return_requests')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index(op.f('ix_quality_control_records_shipment_id'), table_name='quality_control_records')
    op.drop_index(op.f('ix_quality_control_records_item_id'), table_name='quality_control_records')
    op.drop_table('quality_control_records')
    op.drop_index(op.f('ix_damage_records_warehouse_id'), table_name='damage_records')
    op.drop_index(op.f('ix_damage_records_timestamp'), table_name='damage_records')
    op.drop_index(op.f('ix_damage_records_location_id'), table_name='damage_records')
    op.drop_index(op.f('ix_damage_records_item_id'), table_name='damage_records')
    op.drop_table('damage_records')
    op.drop_index(op.f('ix_transfer_requests_status'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_source_warehouse_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_destination_warehouse_id'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    # ### end Alembic commands ###
