"""add_pathfinding_tables

Revision ID: eb5571a52c39
Revises: dbf8748ff321
Create Date: 2026-08-18 20:12:19.917158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5571a52c39'
down_revision: Union[str, Sequence[str], None] = 'dbf8748ff321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_grid_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('cell_type', sa.String(length=30), nullable=False),
    sa.Column('traversable', sa.Boolean(), nullable=False),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'x', 'y', name='uq_grid_cell')
    )
    op.create_index(op.f('ix_warehouse_grid_cells_warehouse_id'), 'warehouse_grid_cells', ['warehouse_id'], unique=False)
    op.create_table('warehouse_obstacles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('obstacle_type', sa.String(length=30), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_obstacles_warehouse_id'), 'warehouse_obstacles', ['warehouse_id'], unique=False)
    op.create_table('robot_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_reservations_robot_id'), 'robot_reservations', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_reservations_warehouse_id'), 'robot_reservations', ['warehouse_id'], unique=False)
    op.create_table('robot_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.String(length=20), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('goal_x', sa.Integer(), nullable=False),
    sa.Column('goal_y', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('path_data', sa.Text(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_routes_robot_id'), 'robot_routes', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_routes_task_id'), 'robot_routes', ['task_id'], unique=False)
    op.create_index(op.f('ix_robot_routes_warehouse_id'), 'robot_routes', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_routes_warehouse_id'), table_name='robot_routes')
    op.drop_index(op.f('ix_robot_routes_task_id'), table_name='robot_routes')
    op.drop_index(op.f('ix_robot_routes_robot_id'), table_name='robot_routes')
    op.drop_table('robot_routes')
    op.drop_index(op.f('ix_robot_reservations_warehouse_id'), table_name='robot_reservations')
    op.drop_index(op.f('ix_robot_reservations_robot_id'), table_name='robot_reservations')
    op.drop_table('robot_reservations')
    op.drop_index(op.f('ix_warehouse_obstacles_warehouse_id'), table_name='warehouse_obstacles')
    op.drop_table('warehouse_obstacles')
    op.drop_index(op.f('ix_warehouse_grid_cells_warehouse_id'), table_name='warehouse_grid_cells')
    op.drop_table('warehouse_grid_cells')
    # ### end Alembic commands ###
